
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ""
  username: araliz

development:
  <<: *default
  database: atelier_development


test:
  <<: *default
  database: atelier_test


production:
  <<: *default
  database: atelier_production
